// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster/cluster_services.proto

package cluster

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegionRequest struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegionRequest) Reset()         { *m = RegionRequest{} }
func (m *RegionRequest) String() string { return proto.CompactTextString(m) }
func (*RegionRequest) ProtoMessage()    {}
func (*RegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e508423385bc46d, []int{0}
}

func (m *RegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionRequest.Unmarshal(m, b)
}
func (m *RegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionRequest.Marshal(b, m, deterministic)
}
func (m *RegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionRequest.Merge(m, src)
}
func (m *RegionRequest) XXX_Size() int {
	return xxx_messageInfo_RegionRequest.Size(m)
}
func (m *RegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegionRequest proto.InternalMessageInfo

func (m *RegionRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type ClusterId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterId) Reset()         { *m = ClusterId{} }
func (m *ClusterId) String() string { return proto.CompactTextString(m) }
func (*ClusterId) ProtoMessage()    {}
func (*ClusterId) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e508423385bc46d, []int{1}
}

func (m *ClusterId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterId.Unmarshal(m, b)
}
func (m *ClusterId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterId.Marshal(b, m, deterministic)
}
func (m *ClusterId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterId.Merge(m, src)
}
func (m *ClusterId) XXX_Size() int {
	return xxx_messageInfo_ClusterId.Size(m)
}
func (m *ClusterId) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterId.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterId proto.InternalMessageInfo

func (m *ClusterId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ClusterCredentials struct {
	Credentials          []byte   `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterCredentials) Reset()         { *m = ClusterCredentials{} }
func (m *ClusterCredentials) String() string { return proto.CompactTextString(m) }
func (*ClusterCredentials) ProtoMessage()    {}
func (*ClusterCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e508423385bc46d, []int{2}
}

func (m *ClusterCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterCredentials.Unmarshal(m, b)
}
func (m *ClusterCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterCredentials.Marshal(b, m, deterministic)
}
func (m *ClusterCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterCredentials.Merge(m, src)
}
func (m *ClusterCredentials) XXX_Size() int {
	return xxx_messageInfo_ClusterCredentials.Size(m)
}
func (m *ClusterCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterCredentials proto.InternalMessageInfo

func (m *ClusterCredentials) GetCredentials() []byte {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func init() {
	proto.RegisterType((*RegionRequest)(nil), "cluster.RegionRequest")
	proto.RegisterType((*ClusterId)(nil), "cluster.ClusterId")
	proto.RegisterType((*ClusterCredentials)(nil), "cluster.ClusterCredentials")
}

func init() { proto.RegisterFile("cluster/cluster_services.proto", fileDescriptor_6e508423385bc46d) }

var fileDescriptor_6e508423385bc46d = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0xce, 0x29, 0x2d,
	0x2e, 0x49, 0x2d, 0xd2, 0x87, 0xd2, 0xf1, 0xc5, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0xc5, 0x7a,
	0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0x71, 0x25, 0x75, 0x2e, 0xde, 0xa0, 0xd4, 0xf4,
	0xcc, 0xfc, 0xbc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x31, 0x2e, 0xb6, 0x22, 0xb0,
	0x80, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x94, 0xa7, 0x24, 0xcd, 0xc5, 0xe9, 0x0c, 0xd1,
	0xe3, 0x99, 0x22, 0xc4, 0xc7, 0xc5, 0x94, 0x99, 0x02, 0x55, 0xc0, 0x94, 0x99, 0xa2, 0x64, 0xc6,
	0x25, 0x04, 0x95, 0x74, 0x2e, 0x4a, 0x4d, 0x49, 0xcd, 0x2b, 0xc9, 0x4c, 0xcc, 0x29, 0x16, 0x52,
	0xe0, 0xe2, 0x4e, 0x46, 0x70, 0xc1, 0xca, 0x79, 0x82, 0x90, 0x85, 0x8c, 0xa6, 0x31, 0x72, 0xf1,
	0x41, 0x35, 0x06, 0x43, 0x1c, 0x28, 0xe4, 0xc8, 0xc5, 0xe7, 0x9e, 0x5a, 0x82, 0x6c, 0x8c, 0x90,
	0x1e, 0xd4, 0xb1, 0x7a, 0x70, 0x07, 0x48, 0x49, 0xa3, 0x8b, 0x21, 0x6b, 0x70, 0xe4, 0x12, 0x06,
	0x19, 0x01, 0x91, 0x70, 0xcb, 0x2f, 0x82, 0x78, 0x50, 0x48, 0x0c, 0xae, 0x07, 0xc5, 0xc7, 0x52,
	0x58, 0xcc, 0x77, 0xe2, 0x8d, 0xe2, 0x4e, 0x2c, 0xc8, 0x84, 0x85, 0x5e, 0x12, 0x1b, 0x38, 0xd4,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x52, 0x99, 0x65, 0x12, 0x57, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterServiceClient interface {
	GetCredentials(ctx context.Context, in *ClusterId, opts ...grpc.CallOption) (*ClusterCredentials, error)
	GetClusterForRegion(ctx context.Context, in *RegionRequest, opts ...grpc.CallOption) (*ClusterId, error)
}

type clusterServiceClient struct {
	cc *grpc.ClientConn
}

func NewClusterServiceClient(cc *grpc.ClientConn) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) GetCredentials(ctx context.Context, in *ClusterId, opts ...grpc.CallOption) (*ClusterCredentials, error) {
	out := new(ClusterCredentials)
	err := c.cc.Invoke(ctx, "/cluster.ClusterService/GetCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) GetClusterForRegion(ctx context.Context, in *RegionRequest, opts ...grpc.CallOption) (*ClusterId, error) {
	out := new(ClusterId)
	err := c.cc.Invoke(ctx, "/cluster.ClusterService/GetClusterForRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
type ClusterServiceServer interface {
	GetCredentials(context.Context, *ClusterId) (*ClusterCredentials, error)
	GetClusterForRegion(context.Context, *RegionRequest) (*ClusterId, error)
}

// UnimplementedClusterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClusterServiceServer struct {
}

func (*UnimplementedClusterServiceServer) GetCredentials(ctx context.Context, req *ClusterId) (*ClusterCredentials, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCredentials not implemented")
}
func (*UnimplementedClusterServiceServer) GetClusterForRegion(ctx context.Context, req *RegionRequest) (*ClusterId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterForRegion not implemented")
}

func RegisterClusterServiceServer(s *grpc.Server, srv ClusterServiceServer) {
	s.RegisterService(&_ClusterService_serviceDesc, srv)
}

func _ClusterService_GetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.ClusterService/GetCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetCredentials(ctx, req.(*ClusterId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_GetClusterForRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetClusterForRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.ClusterService/GetClusterForRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetClusterForRegion(ctx, req.(*RegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cluster.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCredentials",
			Handler:    _ClusterService_GetCredentials_Handler,
		},
		{
			MethodName: "GetClusterForRegion",
			Handler:    _ClusterService_GetClusterForRegion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster/cluster_services.proto",
}
