// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster/cluster_services.proto

package cluster

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClusterGroup_ClusterGroupType int32

const (
	ClusterGroup_KUBERNETES ClusterGroup_ClusterGroupType = 0
	ClusterGroup_AWS        ClusterGroup_ClusterGroupType = 1
	ClusterGroup_AZURE      ClusterGroup_ClusterGroupType = 2
	ClusterGroup_GOOGLE     ClusterGroup_ClusterGroupType = 3
)

var ClusterGroup_ClusterGroupType_name = map[int32]string{
	0: "KUBERNETES",
	1: "AWS",
	2: "AZURE",
	3: "GOOGLE",
}

var ClusterGroup_ClusterGroupType_value = map[string]int32{
	"KUBERNETES": 0,
	"AWS":        1,
	"AZURE":      2,
	"GOOGLE":     3,
}

func (x ClusterGroup_ClusterGroupType) String() string {
	return proto.EnumName(ClusterGroup_ClusterGroupType_name, int32(x))
}

func (ClusterGroup_ClusterGroupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6e508423385bc46d, []int{3, 0}
}

type RegionRequest struct {
	Region               string   `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegionRequest) Reset()         { *m = RegionRequest{} }
func (m *RegionRequest) String() string { return proto.CompactTextString(m) }
func (*RegionRequest) ProtoMessage()    {}
func (*RegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e508423385bc46d, []int{0}
}

func (m *RegionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegionRequest.Unmarshal(m, b)
}
func (m *RegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegionRequest.Marshal(b, m, deterministic)
}
func (m *RegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegionRequest.Merge(m, src)
}
func (m *RegionRequest) XXX_Size() int {
	return xxx_messageInfo_RegionRequest.Size(m)
}
func (m *RegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegionRequest proto.InternalMessageInfo

func (m *RegionRequest) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type ClusterId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterId) Reset()         { *m = ClusterId{} }
func (m *ClusterId) String() string { return proto.CompactTextString(m) }
func (*ClusterId) ProtoMessage()    {}
func (*ClusterId) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e508423385bc46d, []int{1}
}

func (m *ClusterId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterId.Unmarshal(m, b)
}
func (m *ClusterId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterId.Marshal(b, m, deterministic)
}
func (m *ClusterId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterId.Merge(m, src)
}
func (m *ClusterId) XXX_Size() int {
	return xxx_messageInfo_ClusterId.Size(m)
}
func (m *ClusterId) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterId.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterId proto.InternalMessageInfo

func (m *ClusterId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Cluster struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProvisionerImage     string        `protobuf:"bytes,2,opt,name=provisionerImage,proto3" json:"provisionerImage,omitempty"`
	Credentials          []byte        `protobuf:"bytes,3,opt,name=credentials,proto3" json:"credentials,omitempty"`
	ClusterGroup         *ClusterGroup `protobuf:"bytes,4,opt,name=clusterGroup,proto3" json:"clusterGroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e508423385bc46d, []int{2}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Cluster) GetProvisionerImage() string {
	if m != nil {
		return m.ProvisionerImage
	}
	return ""
}

func (m *Cluster) GetCredentials() []byte {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *Cluster) GetClusterGroup() *ClusterGroup {
	if m != nil {
		return m.ClusterGroup
	}
	return nil
}

type ClusterGroup struct {
	Id                   string                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Region               string                        `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Type                 ClusterGroup_ClusterGroupType `protobuf:"varint,3,opt,name=type,proto3,enum=cluster.ClusterGroup_ClusterGroupType" json:"type,omitempty"`
	Credentials          []byte                        `protobuf:"bytes,4,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Data                 []byte                        `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ClusterGroup) Reset()         { *m = ClusterGroup{} }
func (m *ClusterGroup) String() string { return proto.CompactTextString(m) }
func (*ClusterGroup) ProtoMessage()    {}
func (*ClusterGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e508423385bc46d, []int{3}
}

func (m *ClusterGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterGroup.Unmarshal(m, b)
}
func (m *ClusterGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterGroup.Marshal(b, m, deterministic)
}
func (m *ClusterGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterGroup.Merge(m, src)
}
func (m *ClusterGroup) XXX_Size() int {
	return xxx_messageInfo_ClusterGroup.Size(m)
}
func (m *ClusterGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterGroup.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterGroup proto.InternalMessageInfo

func (m *ClusterGroup) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClusterGroup) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *ClusterGroup) GetType() ClusterGroup_ClusterGroupType {
	if m != nil {
		return m.Type
	}
	return ClusterGroup_KUBERNETES
}

func (m *ClusterGroup) GetCredentials() []byte {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *ClusterGroup) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("cluster.ClusterGroup_ClusterGroupType", ClusterGroup_ClusterGroupType_name, ClusterGroup_ClusterGroupType_value)
	proto.RegisterType((*RegionRequest)(nil), "cluster.RegionRequest")
	proto.RegisterType((*ClusterId)(nil), "cluster.ClusterId")
	proto.RegisterType((*Cluster)(nil), "cluster.Cluster")
	proto.RegisterType((*ClusterGroup)(nil), "cluster.ClusterGroup")
}

func init() { proto.RegisterFile("cluster/cluster_services.proto", fileDescriptor_6e508423385bc46d) }

var fileDescriptor_6e508423385bc46d = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x6a, 0xea, 0x40,
	0x14, 0x86, 0xef, 0xc4, 0xa8, 0x78, 0xd4, 0x90, 0x7b, 0x2e, 0x57, 0x82, 0x17, 0x2e, 0x21, 0x8b,
	0x56, 0xba, 0xb0, 0x60, 0x57, 0x76, 0xa7, 0x36, 0x0d, 0xd2, 0x52, 0x61, 0x54, 0x0a, 0x6e, 0x4a,
	0x6a, 0x06, 0x19, 0xb0, 0x26, 0x9d, 0x8c, 0x82, 0x2f, 0xd1, 0x87, 0xe8, 0xf3, 0xf5, 0x21, 0x4a,
	0xc7, 0x69, 0x8d, 0xd1, 0x55, 0x32, 0xdf, 0x7f, 0xce, 0x99, 0xf3, 0x33, 0x3f, 0xfc, 0x9f, 0x2f,
	0xd7, 0xa9, 0x64, 0xe2, 0x52, 0x7f, 0x9f, 0x52, 0x26, 0x36, 0x7c, 0xce, 0xd2, 0x76, 0x22, 0x62,
	0x19, 0x63, 0x59, 0x73, 0xef, 0x1c, 0xea, 0x94, 0x2d, 0x78, 0xbc, 0xa2, 0xec, 0x75, 0xcd, 0x52,
	0x89, 0x0d, 0x28, 0x09, 0x05, 0x1c, 0xe2, 0x92, 0x56, 0x85, 0xea, 0x93, 0xf7, 0x0f, 0x2a, 0x83,
	0x5d, 0xcf, 0x30, 0x42, 0x0b, 0x0c, 0x1e, 0xe9, 0x02, 0x83, 0x47, 0xde, 0x3b, 0x81, 0xb2, 0x56,
	0xf3, 0x1a, 0x5e, 0x80, 0x9d, 0x88, 0x78, 0xc3, 0x53, 0x1e, 0xaf, 0x98, 0x18, 0xbe, 0x84, 0x0b,
	0xe6, 0x18, 0x4a, 0x3d, 0xe2, 0xe8, 0x42, 0x75, 0x2e, 0x58, 0xc4, 0x56, 0x92, 0x87, 0xcb, 0xd4,
	0x29, 0xb8, 0xa4, 0x55, 0xa3, 0x59, 0x84, 0x5d, 0xa8, 0xe9, 0xd5, 0x03, 0x11, 0xaf, 0x13, 0xc7,
	0x74, 0x49, 0xab, 0xda, 0xf9, 0xdb, 0xd6, 0xb0, 0x3d, 0xc8, 0x88, 0xf4, 0xa0, 0xd4, 0xfb, 0x20,
	0x50, 0xcb, 0xca, 0x47, 0x9b, 0xee, 0xad, 0x1b, 0x59, 0xeb, 0x78, 0x0d, 0xa6, 0xdc, 0x26, 0x4c,
	0xad, 0x63, 0x75, 0xce, 0x4e, 0xde, 0x75, 0x70, 0x98, 0x6c, 0x13, 0x46, 0x55, 0x4f, 0xde, 0x91,
	0x79, 0xec, 0x08, 0xc1, 0x8c, 0x42, 0x19, 0x3a, 0x45, 0x25, 0xa9, 0x7f, 0xaf, 0x0f, 0x76, 0x7e,
	0x1e, 0x5a, 0x00, 0x77, 0xd3, 0xbe, 0x4f, 0x1f, 0xfc, 0x89, 0x3f, 0xb6, 0x7f, 0x61, 0x19, 0x0a,
	0xbd, 0xc7, 0xb1, 0x4d, 0xb0, 0x02, 0xc5, 0xde, 0x6c, 0x4a, 0x7d, 0xdb, 0x40, 0x80, 0x52, 0x30,
	0x1a, 0x05, 0xf7, 0xbe, 0x5d, 0xe8, 0xbc, 0x11, 0xb0, 0xf4, 0x90, 0xf1, 0xee, 0xf1, 0xb1, 0x0b,
	0xbf, 0x03, 0x26, 0x35, 0xbc, 0x61, 0x32, 0xe4, 0x5f, 0xf7, 0xe7, 0xfd, 0x0c, 0xa3, 0xa6, 0x9d,
	0x67, 0xd8, 0x83, 0x3f, 0xfb, 0xd6, 0xdb, 0x58, 0xec, 0x42, 0x83, 0x8d, 0x9f, 0xc2, 0x83, 0x14,
	0x35, 0x4f, 0x0c, 0xed, 0xd7, 0x67, 0xd5, 0x30, 0xe1, 0xdf, 0x89, 0x7c, 0x2e, 0xa9, 0x24, 0x5e,
	0x7d, 0x06, 0x00, 0x00, 0xff, 0xff, 0x92, 0x81, 0xe9, 0x3e, 0xab, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterServiceClient is the client API for ClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterServiceClient interface {
	GetClusterDetails(ctx context.Context, in *ClusterId, opts ...grpc.CallOption) (*Cluster, error)
	GetClusterForRegion(ctx context.Context, in *RegionRequest, opts ...grpc.CallOption) (*ClusterId, error)
}

type clusterServiceClient struct {
	cc *grpc.ClientConn
}

func NewClusterServiceClient(cc *grpc.ClientConn) ClusterServiceClient {
	return &clusterServiceClient{cc}
}

func (c *clusterServiceClient) GetClusterDetails(ctx context.Context, in *ClusterId, opts ...grpc.CallOption) (*Cluster, error) {
	out := new(Cluster)
	err := c.cc.Invoke(ctx, "/cluster.ClusterService/GetClusterDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clusterServiceClient) GetClusterForRegion(ctx context.Context, in *RegionRequest, opts ...grpc.CallOption) (*ClusterId, error) {
	out := new(ClusterId)
	err := c.cc.Invoke(ctx, "/cluster.ClusterService/GetClusterForRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServiceServer is the server API for ClusterService service.
type ClusterServiceServer interface {
	GetClusterDetails(context.Context, *ClusterId) (*Cluster, error)
	GetClusterForRegion(context.Context, *RegionRequest) (*ClusterId, error)
}

// UnimplementedClusterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClusterServiceServer struct {
}

func (*UnimplementedClusterServiceServer) GetClusterDetails(ctx context.Context, req *ClusterId) (*Cluster, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterDetails not implemented")
}
func (*UnimplementedClusterServiceServer) GetClusterForRegion(ctx context.Context, req *RegionRequest) (*ClusterId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterForRegion not implemented")
}

func RegisterClusterServiceServer(s *grpc.Server, srv ClusterServiceServer) {
	s.RegisterService(&_ClusterService_serviceDesc, srv)
}

func _ClusterService_GetClusterDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetClusterDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.ClusterService/GetClusterDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetClusterDetails(ctx, req.(*ClusterId))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClusterService_GetClusterForRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServiceServer).GetClusterForRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cluster.ClusterService/GetClusterForRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServiceServer).GetClusterForRegion(ctx, req.(*RegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClusterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cluster.ClusterService",
	HandlerType: (*ClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterDetails",
			Handler:    _ClusterService_GetClusterDetails_Handler,
		},
		{
			MethodName: "GetClusterForRegion",
			Handler:    _ClusterService_GetClusterForRegion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster/cluster_services.proto",
}
