name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1      
    - name: Clone Gitlab.com caspr-io/root
      run: git clone https://gitlab-ci-token:${GITLAB_PAT}@gitlab.com/caspr-io/root ../root
      env:
        GITLAB_PAT: ${{secrets.GITLAB_PAT}}
    - name: Make docker image
      run: make build
